<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GcrWantsUrl', 'doctrine');

/**
 * BaseGcrWantsUrl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $time_created
 * @property string $wants_url
 * @property string $redirect_type
 * @property string $app_id
 * 
 * @method integer     getId()            Returns the current record's "id" value
 * @method integer     getTimeCreated()   Returns the current record's "time_created" value
 * @method string      getWantsUrl()      Returns the current record's "wants_url" value
 * @method string      getRedirectType()  Returns the current record's "redirect_type" value
 * @method string      getAppId()         Returns the current record's "app_id" value
 * @method GcrWantsUrl setId()            Sets the current record's "id" value
 * @method GcrWantsUrl setTimeCreated()   Sets the current record's "time_created" value
 * @method GcrWantsUrl setWantsUrl()      Sets the current record's "wants_url" value
 * @method GcrWantsUrl setRedirectType()  Sets the current record's "redirect_type" value
 * @method GcrWantsUrl setAppId()         Sets the current record's "app_id" value
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGcrWantsUrl extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gcr_wants_url');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'gcr_wants_url_id',
             'length' => 8,
             ));
        $this->hasColumn('time_created', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('wants_url', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('redirect_type', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('app_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}