<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GcrPerson', 'doctrine');

/**
 * BaseGcrPerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $first_name
 * @property string $last_name
 * @property integer $address
 * @property string $phone1
 * @property string $phone2
 * @property string $email
 * 
 * @method integer   getId()         Returns the current record's "id" value
 * @method string    getFirstName()  Returns the current record's "first_name" value
 * @method string    getLastName()   Returns the current record's "last_name" value
 * @method integer   getAddress()    Returns the current record's "address" value
 * @method string    getPhone1()     Returns the current record's "phone1" value
 * @method string    getPhone2()     Returns the current record's "phone2" value
 * @method string    getEmail()      Returns the current record's "email" value
 * @method GcrPerson setId()         Sets the current record's "id" value
 * @method GcrPerson setFirstName()  Sets the current record's "first_name" value
 * @method GcrPerson setLastName()   Sets the current record's "last_name" value
 * @method GcrPerson setAddress()    Sets the current record's "address" value
 * @method GcrPerson setPhone1()     Sets the current record's "phone1" value
 * @method GcrPerson setPhone2()     Sets the current record's "phone2" value
 * @method GcrPerson setEmail()      Sets the current record's "email" value
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGcrPerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gcr_person');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'gcr_person_id',
             'length' => 8,
             ));
        $this->hasColumn('first_name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('last_name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('address', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('phone1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('phone2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('email', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}