<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GcrPayoffCredentials', 'doctrine');

/**
 * BaseGcrPayoffCredentials
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $user_business_name
 * @property string $user_first_name
 * @property string $user_last_name
 * @property string $user_paypal_email
 * @property string $user_tin
 * @property string $user_eschool_id
 * @property integer $user_id
 * @property string $verify_status
 * @property string $verify_hash
 * 
 * @method integer              getId()                 Returns the current record's "id" value
 * @method string               getUserBusinessName()   Returns the current record's "user_business_name" value
 * @method string               getUserFirstName()      Returns the current record's "user_first_name" value
 * @method string               getUserLastName()       Returns the current record's "user_last_name" value
 * @method string               getUserPaypalEmail()    Returns the current record's "user_paypal_email" value
 * @method string               getUserTin()            Returns the current record's "user_tin" value
 * @method string               getUserEschoolId()      Returns the current record's "user_eschool_id" value
 * @method integer              getUserId()             Returns the current record's "user_id" value
 * @method string               getVerifyStatus()       Returns the current record's "verify_status" value
 * @method string               getVerifyHash()         Returns the current record's "verify_hash" value
 * @method GcrPayoffCredentials setId()                 Sets the current record's "id" value
 * @method GcrPayoffCredentials setUserBusinessName()   Sets the current record's "user_business_name" value
 * @method GcrPayoffCredentials setUserFirstName()      Sets the current record's "user_first_name" value
 * @method GcrPayoffCredentials setUserLastName()       Sets the current record's "user_last_name" value
 * @method GcrPayoffCredentials setUserPaypalEmail()    Sets the current record's "user_paypal_email" value
 * @method GcrPayoffCredentials setUserTin()            Sets the current record's "user_tin" value
 * @method GcrPayoffCredentials setUserEschoolId()      Sets the current record's "user_eschool_id" value
 * @method GcrPayoffCredentials setUserId()             Sets the current record's "user_id" value
 * @method GcrPayoffCredentials setVerifyStatus()       Sets the current record's "verify_status" value
 * @method GcrPayoffCredentials setVerifyHash()         Sets the current record's "verify_hash" value
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGcrPayoffCredentials extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gcr_payoff_credentials');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'gcr_payoff_credentials_id',
             'length' => 8,
             ));
        $this->hasColumn('user_business_name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('user_first_name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('user_last_name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('user_paypal_email', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('user_tin', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('user_eschool_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('verify_status', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => 'unverified',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('verify_hash', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}