<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GcrChainedPayment', 'doctrine');

/**
 * BaseGcrChainedPayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $user_institution_id
 * 
 * @method integer           getId()                  Returns the current record's "id" value
 * @method integer           getUserId()              Returns the current record's "user_id" value
 * @method string            getUserInstitutionId()   Returns the current record's "user_institution_id" value
 * @method GcrChainedPayment setId()                  Sets the current record's "id" value
 * @method GcrChainedPayment setUserId()              Sets the current record's "user_id" value
 * @method GcrChainedPayment setUserInstitutionId()   Sets the current record's "user_institution_id" value
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGcrChainedPayment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gcr_chained_payment');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'gcr_chained_payment_id',
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('user_institution_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}