<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GcrPurchase', 'doctrine');

/**
 * BaseGcrPurchase
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $purchase_type
 * @property string $purchase_type_id
 * @property string $purchase_type_eschool_id
 * @property integer $trans_time
 * @property string $user_institution_id
 * @property integer $user_id
 * @property decimal $amount
 * @property string $bill_cycle
 * @property string $profile_id
 * @property decimal $gc_fee
 * @property decimal $owner_fee
 * @property decimal $commission_fee
 * @property integer $seller_id
 * @property string $seller_institution_id
 * @property string $purchase_type_description
 * @property integer $purchase_type_quantity
 * 
 * @method integer     getId()                        Returns the current record's "id" value
 * @method string      getPurchaseType()              Returns the current record's "purchase_type" value
 * @method string      getPurchaseTypeId()            Returns the current record's "purchase_type_id" value
 * @method string      getPurchaseTypeEschoolId()     Returns the current record's "purchase_type_eschool_id" value
 * @method integer     getTransTime()                 Returns the current record's "trans_time" value
 * @method string      getUserInstitutionId()         Returns the current record's "user_institution_id" value
 * @method integer     getUserId()                    Returns the current record's "user_id" value
 * @method decimal     getAmount()                    Returns the current record's "amount" value
 * @method string      getBillCycle()                 Returns the current record's "bill_cycle" value
 * @method string      getProfileId()                 Returns the current record's "profile_id" value
 * @method decimal     getGcFee()                     Returns the current record's "gc_fee" value
 * @method decimal     getOwnerFee()                  Returns the current record's "owner_fee" value
 * @method decimal     getCommissionFee()             Returns the current record's "commission_fee" value
 * @method integer     getSellerId()                  Returns the current record's "seller_id" value
 * @method string      getSellerInstitutionId()       Returns the current record's "seller_institution_id" value
 * @method string      getPurchaseTypeDescription()   Returns the current record's "purchase_type_description" value
 * @method integer     getPurchaseTypeQuantity()      Returns the current record's "purchase_type_quantity" value
 * @method GcrPurchase setId()                        Sets the current record's "id" value
 * @method GcrPurchase setPurchaseType()              Sets the current record's "purchase_type" value
 * @method GcrPurchase setPurchaseTypeId()            Sets the current record's "purchase_type_id" value
 * @method GcrPurchase setPurchaseTypeEschoolId()     Sets the current record's "purchase_type_eschool_id" value
 * @method GcrPurchase setTransTime()                 Sets the current record's "trans_time" value
 * @method GcrPurchase setUserInstitutionId()         Sets the current record's "user_institution_id" value
 * @method GcrPurchase setUserId()                    Sets the current record's "user_id" value
 * @method GcrPurchase setAmount()                    Sets the current record's "amount" value
 * @method GcrPurchase setBillCycle()                 Sets the current record's "bill_cycle" value
 * @method GcrPurchase setProfileId()                 Sets the current record's "profile_id" value
 * @method GcrPurchase setGcFee()                     Sets the current record's "gc_fee" value
 * @method GcrPurchase setOwnerFee()                  Sets the current record's "owner_fee" value
 * @method GcrPurchase setCommissionFee()             Sets the current record's "commission_fee" value
 * @method GcrPurchase setSellerId()                  Sets the current record's "seller_id" value
 * @method GcrPurchase setSellerInstitutionId()       Sets the current record's "seller_institution_id" value
 * @method GcrPurchase setPurchaseTypeDescription()   Sets the current record's "purchase_type_description" value
 * @method GcrPurchase setPurchaseTypeQuantity()      Sets the current record's "purchase_type_quantity" value
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGcrPurchase extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gcr_purchase');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'gcr_purchase_id',
             'length' => 8,
             ));
        $this->hasColumn('purchase_type', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('purchase_type_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('purchase_type_eschool_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'default' => '',
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('trans_time', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('user_institution_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('amount', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0.00',
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('bill_cycle', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'default' => 'single',
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('profile_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'default' => '',
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('gc_fee', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'default' => '0',
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('owner_fee', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'default' => '0',
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('commission_fee', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'default' => '0',
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('seller_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('seller_institution_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('purchase_type_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('purchase_type_quantity', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '1',
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}