<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GcrEclassroom', 'doctrine');

/**
 * BaseGcrEclassroom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $user_institution_id
 * @property string $eschool_id
 * @property string $mhr_institution_name
 * @property boolean $suspended
 * @property integer $user_id
 * @property integer $category_id
 * 
 * @method integer       getId()                   Returns the current record's "id" value
 * @method string        getUserInstitutionId()    Returns the current record's "user_institution_id" value
 * @method string        getEschoolId()            Returns the current record's "eschool_id" value
 * @method string        getMhrInstitutionName()   Returns the current record's "mhr_institution_name" value
 * @method boolean       getSuspended()            Returns the current record's "suspended" value
 * @method integer       getUserId()               Returns the current record's "user_id" value
 * @method integer       getCategoryId()           Returns the current record's "category_id" value
 * @method GcrEclassroom setId()                   Sets the current record's "id" value
 * @method GcrEclassroom setUserInstitutionId()    Sets the current record's "user_institution_id" value
 * @method GcrEclassroom setEschoolId()            Sets the current record's "eschool_id" value
 * @method GcrEclassroom setMhrInstitutionName()   Sets the current record's "mhr_institution_name" value
 * @method GcrEclassroom setSuspended()            Sets the current record's "suspended" value
 * @method GcrEclassroom setUserId()               Sets the current record's "user_id" value
 * @method GcrEclassroom setCategoryId()           Sets the current record's "category_id" value
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGcrEclassroom extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gcr_eclassroom');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'gcr_eclassroom_id',
             'length' => 8,
             ));
        $this->hasColumn('user_institution_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('eschool_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('mhr_institution_name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('suspended', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => 'false',
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}