<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GcrCommission', 'doctrine');

/**
 * BaseGcrCommission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $institution_id
 * @property string $eschool_id
 * @property decimal $commission_rate
 * 
 * @method integer       getId()              Returns the current record's "id" value
 * @method string        getInstitutionId()   Returns the current record's "institution_id" value
 * @method string        getEschoolId()       Returns the current record's "eschool_id" value
 * @method decimal       getCommissionRate()  Returns the current record's "commission_rate" value
 * @method GcrCommission setId()              Sets the current record's "id" value
 * @method GcrCommission setInstitutionId()   Sets the current record's "institution_id" value
 * @method GcrCommission setEschoolId()       Sets the current record's "eschool_id" value
 * @method GcrCommission setCommissionRate()  Sets the current record's "commission_rate" value
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGcrCommission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gcr_commission');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'gcr_commission_id',
             'length' => 8,
             ));
        $this->hasColumn('institution_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('eschool_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('commission_rate', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 18,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}