<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GcrEschool', 'doctrine');

/**
 * BaseGcrEschool
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $full_name
 * @property string $external_url
 * @property boolean $suspended
 * @property string $logo
 * @property boolean $can_sell
 * @property integer $contact1
 * @property integer $contact2
 * @property integer $address
 * @property integer $eschool_type
 * @property boolean $visible
 * @property string $short_name
 * @property string $password_salt
 * @property boolean $reset_keys
 * @property boolean $is_public
 * @property string $admin_password
 * @property integer $eschool_creator
 * @property integer $creation_date
 * @property integer $organization_id
 * 
 * @method integer    getId()              Returns the current record's "id" value
 * @method string     getFullName()        Returns the current record's "full_name" value
 * @method string     getExternalUrl()     Returns the current record's "external_url" value
 * @method boolean    getSuspended()       Returns the current record's "suspended" value
 * @method string     getLogo()            Returns the current record's "logo" value
 * @method boolean    getCanSell()         Returns the current record's "can_sell" value
 * @method integer    getContact1()        Returns the current record's "contact1" value
 * @method integer    getContact2()        Returns the current record's "contact2" value
 * @method integer    getAddress()         Returns the current record's "address" value
 * @method integer    getEschoolType()     Returns the current record's "eschool_type" value
 * @method boolean    getVisible()         Returns the current record's "visible" value
 * @method string     getShortName()       Returns the current record's "short_name" value
 * @method string     getPasswordSalt()    Returns the current record's "password_salt" value
 * @method boolean    getResetKeys()       Returns the current record's "reset_keys" value
 * @method boolean    getIsPublic()        Returns the current record's "is_public" value
 * @method string     getAdminPassword()   Returns the current record's "admin_password" value
 * @method integer    getEschoolCreator()  Returns the current record's "eschool_creator" value
 * @method integer    getCreationDate()    Returns the current record's "creation_date" value
 * @method integer    getOrganizationId()  Returns the current record's "organization_id" value
 * @method GcrEschool setId()              Sets the current record's "id" value
 * @method GcrEschool setFullName()        Sets the current record's "full_name" value
 * @method GcrEschool setExternalUrl()     Sets the current record's "external_url" value
 * @method GcrEschool setSuspended()       Sets the current record's "suspended" value
 * @method GcrEschool setLogo()            Sets the current record's "logo" value
 * @method GcrEschool setCanSell()         Sets the current record's "can_sell" value
 * @method GcrEschool setContact1()        Sets the current record's "contact1" value
 * @method GcrEschool setContact2()        Sets the current record's "contact2" value
 * @method GcrEschool setAddress()         Sets the current record's "address" value
 * @method GcrEschool setEschoolType()     Sets the current record's "eschool_type" value
 * @method GcrEschool setVisible()         Sets the current record's "visible" value
 * @method GcrEschool setShortName()       Sets the current record's "short_name" value
 * @method GcrEschool setPasswordSalt()    Sets the current record's "password_salt" value
 * @method GcrEschool setResetKeys()       Sets the current record's "reset_keys" value
 * @method GcrEschool setIsPublic()        Sets the current record's "is_public" value
 * @method GcrEschool setAdminPassword()   Sets the current record's "admin_password" value
 * @method GcrEschool setEschoolCreator()  Sets the current record's "eschool_creator" value
 * @method GcrEschool setCreationDate()    Sets the current record's "creation_date" value
 * @method GcrEschool setOrganizationId()  Sets the current record's "organization_id" value
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGcrEschool extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gcr_eschool');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'gcr_eschool_id',
             'length' => 8,
             ));
        $this->hasColumn('full_name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('external_url', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('suspended', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => 'false',
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('logo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('can_sell', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => 'false',
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('contact1', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('contact2', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('address', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('eschool_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('visible', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => 'true',
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('short_name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('password_salt', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('reset_keys', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => 'true',
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('is_public', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => 'false',
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('admin_password', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('eschool_creator', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('creation_date', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('organization_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}