<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GcrTrialApplication', 'doctrine');

/**
 * BaseGcrTrialApplication
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $contact
 * @property integer $address
 * @property string $verify_hash
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getContact()     Returns the current record's "contact" value
 * @method integer             getAddress()     Returns the current record's "address" value
 * @method string              getVerifyHash()  Returns the current record's "verify_hash" value
 * @method GcrTrialApplication setId()          Sets the current record's "id" value
 * @method GcrTrialApplication setContact()     Sets the current record's "contact" value
 * @method GcrTrialApplication setAddress()     Sets the current record's "address" value
 * @method GcrTrialApplication setVerifyHash()  Sets the current record's "verify_hash" value
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGcrTrialApplication extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gcr_trial_application');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'gcr_trial_application_id',
             'length' => 8,
             ));
        $this->hasColumn('contact', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('address', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('verify_hash', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}