<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GcrUserStorageS3Account', 'doctrine');

/**
 * BaseGcrUserStorageS3Account
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $access_key_id
 * @property string $secret_access_key
 * 
 * @method integer                 getId()                Returns the current record's "id" value
 * @method string                  getAccessKeyId()       Returns the current record's "access_key_id" value
 * @method string                  getSecretAccessKey()   Returns the current record's "secret_access_key" value
 * @method GcrUserStorageS3Account setId()                Sets the current record's "id" value
 * @method GcrUserStorageS3Account setAccessKeyId()       Sets the current record's "access_key_id" value
 * @method GcrUserStorageS3Account setSecretAccessKey()   Sets the current record's "secret_access_key" value
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGcrUserStorageS3Account extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gcr_user_storage_s3_account');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'gcr_user_storage_s3_account_id',
             'length' => 8,
             ));
        $this->hasColumn('access_key_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('secret_access_key', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}