<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GcrAddress', 'doctrine');

/**
 * BaseGcrAddress
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $street1
 * @property string $street2
 * @property string $city
 * @property string $zipcode
 * @property string $state
 * @property string $country
 * 
 * @method integer    getId()      Returns the current record's "id" value
 * @method string     getStreet1() Returns the current record's "street1" value
 * @method string     getStreet2() Returns the current record's "street2" value
 * @method string     getCity()    Returns the current record's "city" value
 * @method string     getZipcode() Returns the current record's "zipcode" value
 * @method string     getState()   Returns the current record's "state" value
 * @method string     getCountry() Returns the current record's "country" value
 * @method GcrAddress setId()      Sets the current record's "id" value
 * @method GcrAddress setStreet1() Sets the current record's "street1" value
 * @method GcrAddress setStreet2() Sets the current record's "street2" value
 * @method GcrAddress setCity()    Sets the current record's "city" value
 * @method GcrAddress setZipcode() Sets the current record's "zipcode" value
 * @method GcrAddress setState()   Sets the current record's "state" value
 * @method GcrAddress setCountry() Sets the current record's "country" value
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGcrAddress extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gcr_address');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'gcr_address_id',
             'length' => 8,
             ));
        $this->hasColumn('street1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('street2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('city', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('zipcode', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('state', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('country', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}