<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GcrPurchaseItem', 'doctrine');

/**
 * BaseGcrPurchaseItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $short_name
 * @property string $description
 * @property decimal $amount
 * 
 * @method string          getShortName()   Returns the current record's "short_name" value
 * @method string          getDescription() Returns the current record's "description" value
 * @method decimal         getAmount()      Returns the current record's "amount" value
 * @method GcrPurchaseItem setShortName()   Sets the current record's "short_name" value
 * @method GcrPurchaseItem setDescription() Sets the current record's "description" value
 * @method GcrPurchaseItem setAmount()      Sets the current record's "amount" value
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGcrPurchaseItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gcr_purchase_item');
        $this->hasColumn('short_name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'primary' => true,
             'length' => '',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('amount', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0.00',
             'primary' => false,
             'length' => 18,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}