<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GcrChatSessionInvite', 'doctrine');

/**
 * BaseGcrChatSessionInvite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $time_created
 * @property integer $session_id
 * @property integer $user_id
 * @property string $user_eschool_id
 * @property integer $from_user_id
 * @property string $from_user_eschool_id
 * 
 * @method integer              getId()                   Returns the current record's "id" value
 * @method integer              getTimeCreated()          Returns the current record's "time_created" value
 * @method integer              getSessionId()            Returns the current record's "session_id" value
 * @method integer              getUserId()               Returns the current record's "user_id" value
 * @method string               getUserEschoolId()        Returns the current record's "user_eschool_id" value
 * @method integer              getFromUserId()           Returns the current record's "from_user_id" value
 * @method string               getFromUserEschoolId()    Returns the current record's "from_user_eschool_id" value
 * @method GcrChatSessionInvite setId()                   Sets the current record's "id" value
 * @method GcrChatSessionInvite setTimeCreated()          Sets the current record's "time_created" value
 * @method GcrChatSessionInvite setSessionId()            Sets the current record's "session_id" value
 * @method GcrChatSessionInvite setUserId()               Sets the current record's "user_id" value
 * @method GcrChatSessionInvite setUserEschoolId()        Sets the current record's "user_eschool_id" value
 * @method GcrChatSessionInvite setFromUserId()           Sets the current record's "from_user_id" value
 * @method GcrChatSessionInvite setFromUserEschoolId()    Sets the current record's "from_user_eschool_id" value
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGcrChatSessionInvite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gcr_chat_session_invite');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'gcr_chat_session_invite_id',
             'length' => 8,
             ));
        $this->hasColumn('time_created', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('session_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('user_eschool_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('from_user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('from_user_eschool_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}