<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GcrBackgroundProcess', 'doctrine');

/**
 * BaseGcrBackgroundProcess
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $job_data
 * @property string $process_type
 * 
 * @method integer              getId()           Returns the current record's "id" value
 * @method string               getJobData()      Returns the current record's "job_data" value
 * @method string               getProcessType()  Returns the current record's "process_type" value
 * @method GcrBackgroundProcess setId()           Sets the current record's "id" value
 * @method GcrBackgroundProcess setJobData()      Sets the current record's "job_data" value
 * @method GcrBackgroundProcess setProcessType()  Sets the current record's "process_type" value
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGcrBackgroundProcess extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gcr_background_process');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'gcr_background_process_id',
             'length' => 8,
             ));
        $this->hasColumn('job_data', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('process_type', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}