<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GcrReservedNames', 'doctrine');

/**
 * BaseGcrReservedNames
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * 
 * @method integer          getId()   Returns the current record's "id" value
 * @method string           getName() Returns the current record's "name" value
 * @method GcrReservedNames setId()   Sets the current record's "id" value
 * @method GcrReservedNames setName() Sets the current record's "name" value
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGcrReservedNames extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gcr_reserved_names');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'gcr_reserved_names_id',
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}