<?php

/**
 * GcrBackgroundProcessTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GcrBackgroundProcessTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GcrBackgroundProcessTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GcrBackgroundProcess');
    }
}