<?php

/**
 * GcrChainedPaymentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GcrChainedPaymentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GcrChainedPaymentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GcrChainedPayment');
    }
    public static function authorizeChainedPayment($course)
    {
        global $CFG;
        $flag = false;
        $current_user = $CFG->current_app->getCurrentUser();
        $course_institution = $course->getApp()->getInstitution();
        if ($course_institution->getAccountManager()->usesChainedPayments())
        {
            $flag = true;
        }
        else if ($seller = $course->getSeller())
        {   
            if ($seller->getAccountManager()->usesChainedPayments())
            {
                $flag = true;
            }
        }
        if ($current_user->isRemoteUser())
        {
            $user_institution = $current_user->getInstitution();
            if ($user_institution->getAccountManager()->usesChainedPayments())
            {
                $commission = GcrCommissionTable::getCommission($user_institution, $course->getApp());
                if ($commission)
                {
                    $rate = $commission->getCommissionRate();
                    if ($rate > 0 && $rate <= 100)
                    {
                        $flag = true;
                    }
                }
            }
        }
        return $flag;
    }
}