<?php

/**
 * GcrCommission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GcrCommission extends BaseGcrCommission
{
    public function getInstitution()
    {
        return Doctrine::getTable('GcrInstitution')->findOneByShortName($this->institution_id);
    }
    public function getEschool()
    {
        return Doctrine::getTable('GcrEschool')->findOneByShortName($this->eschool_id);
    }
}
