<?php

/**
 * GcrChatSessionUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GcrChatSessionUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GcrChatSessionUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GcrChatSessionUsers');
    }
}