<?php

/**
 * GcrChatSessionUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GcrChatSessionUsers extends BaseGcrChatSessionUsers
{
    public function getChatSession()
    {
        return GcrChatSessionTable::getInstance()->find($this->session_id);
    }
    public function getOtherUsers()
    {
        $this_user = $this->getUser();
        $other_user_chat_sessions = GcrChatSessionUsersTable::getInstance()->createQuery('c')
                ->where('c.session_id = ?', $this->session_id)
                ->andWhere('c.user_id != ?', $this_user->getObject()->id)
                ->orWhere('c.user_eschool_id != ?', $this_user->getApp()->getShortName())
                ->orderBy('c.time_created')
                ->execute();
        $users = array();
        foreach ($other_user_chat_sessions as $user_chat_session)
        {
            if ($user = $user_chat_session->getUser())
            {
                if ($user->isLoggedIn())
                {
                    $users[] = $user;
                }
                else
                {
                    $user_chat_session->delete();
                }
            }
        }
        if (count($users) > 0)
        {
            return $users;
        }
        return false;
    }
    public function getUser()
    {
        $institution = Doctrine::getTable('GcrInstitution')->findOneByShortName($this->user_eschool_id);
        return $institution->getUserById($this->user_id);
    }
}
