<?php

/**
 * GcrChatSessionInvite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GcrChatSessionInvite extends BaseGcrChatSessionInvite
{
    public function createUserSession()
    {
        try
        {
            $chat_session = $this->getChatSession();
            $chat_session->getApp()->beginTransaction();
            $chat_session->createUserSession($this->getUser());
            $this->delete();
            $chat_session->getApp()->commitTransaction();
        }
        catch (Doctrine_Exception $e)
        {
            $chat_session->getApp()->rollbackTransaction();
            global $CFG;
            $CFG->current_app->gcError($e->getMessage(), 'gcdatabaseerror');
        }
    }
    public function getChatSession()
    {
        return GcrChatSessionTable::getInstance()->find($this->session_id);
    }
    public function getUser()
    {
        $institution = Doctrine::getTable('GcrInstitution')->findOneByShortName($this->user_eschool_id);
        return $institution->getUserById($this->user_id);
    }
    public function getFromUser()
    {
        $institution = Doctrine::getTable('GcrInstitution')->findOneByShortName($this->from_user_eschool_id);
        return $institution->getUserById($this->from_user_id);
    }
    public function getFromUserHtml()
    {

        $from_user = $this->getFromUser();
        $from_user_obj = $from_user->getObject();
        $app_url = $from_user->getApp()->getAppUrl();
        return '<a style="text-decoration:none" class="gc_user_chat_profile" href="' . $app_url . 'user/view.php?id=' . $from_user_obj->id . '"><br /><img src="' . $from_user->getProfileIcon() . '" /><b>' . $from_user->getFullNameString() . '</b></a><br /><br />requests a new video conference with you<br /><br /><br />';
    }
}
