<?php

/**
 * EschoolType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Justin England
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class GcrEschoolType extends BaseGcrEschoolType
{
    public function getTemplateObject()
    {
        return Doctrine::getTable('GcrEschool')->findOneByShortName($this->template);
    }
}
