<?php

/**
 * GcrEclassroomTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GcrEclassroomTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GcrEclassroomTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GcrEclassroom');
    }
}