<?php

/**
 * GcrInstitutionSaltHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GcrInstitutionSaltHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GcrInstitutionSaltHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GcrInstitutionSaltHistory');
    }
}