<?php

/**
 * PayoffCredentials
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Justin England
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GcrPayoffCredentials extends BaseGcrPayoffCredentials
{
	public function getFullName()
	{
		if (trim($this->user_first_name) != '')
		{
			$full_name = $this->user_first_name; 
		}
		if (trim($this->user_last_name) != '')
		{
			if ($full_name)
			{
				$full_name .= ' ';
			}
			$full_name .= $this->user_last_name; 
		}
		return $full_name;
	}
}
