<?php

/**
 * GcrTrialApplication
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GcrTrialApplication extends BaseGcrTrialApplication
{
    public function isVerified()
    {
        return ($this->verify_hash == 'verified');
    }
    public function getContactObject()
    {
        return Doctrine::getTable('GcrPerson')->find($this->contact);
    }
    public function getAddressObject()
    {
        return Doctrine::getTable('GcrAddress')->find($this->address);
    }
}
