<?php

/**
 * GcrTrialApplicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GcrTrialApplicationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GcrTrialApplicationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GcrTrialApplication');
    }
}