<?php

/**
 * GcrUserStorageS3AccountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GcrUserStorageS3AccountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GcrUserStorageS3AccountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GcrUserStorageS3Account');
    }
}