<?php

/**
 * GcrUserStorageS3
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GcrUserStorageS3 extends BaseGcrUserStorageS3
{
    public function getAccount()
    {
        return Doctrine::getTable('GcrUserStorageS3Account')->find($this->account_id);
    }
}
