<?php

/**
 * GcrUserMonthlyDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GcrUserMonthlyDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GcrUserMonthlyDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GcrUserMonthlyData');
    }
}