<?php

/**
 * GcrWantsUrl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GcrWantsUrl extends BaseGcrWantsUrl
{
    protected $type_strategy;

    public function construct()
    {
        $this->type_strategy = false;
        if (isset($this->redirect_type))
        {
            $this->type_strategy = GcrWantsUrlType::getInstance($this);
        }
    }
    public function toGetParam()
    {
        return GcrWantsUrlType::KEY . '=' . $this->id;
    }
    public function getRedirectUrl()
    {
        if ($app = $this->getApp())
        {
            return $app->getUrl() . $this->wants_url;
        }
        return false;
    }
    public function getTypeStrategy()
    {
        return $this->type_strategy;
    }
    public function setTypeStrategy($redirect_type)
    {
        $this->redirect_type = $redirect_type;
        $this->type_strategy = GcrWantsUrlType::getInstance($this);
    }
    public function getApp()
    {
        return GcrInstitutionTable::getApp($this->app_id);
    }
}
